// Generated by LiveScript 1.4.0
/**
 * User: pilagod
 * Date: 7/10/15
 * Time: 10:29 PM
 */
(function(){
  var React, TodoApp;
  React = require('react');
  TodoApp = require('./components/TodoApp-React');
  React.render(<TodoApp />, document.getElementById('todoapp'));
}).call(this);
