// Generated by LiveScript 1.4.0
/**
 * User: pilagod
 * Date: 7/9/15
 * Time: 11:58 PM
 */
(function(){
  var keyMirror;
  keyMirror = require('keymirror');
  module.exports = keyMirror({
    TODO_CREATE: null,
    TODO_COMPLETE: null,
    TODO_DESTROY: null,
    TODO_DESTROY_COMPLETED: null,
    TODO_TOGGLE_COMPLETE_ALL: null,
    TODO_UNDO_COMPLETE: null,
    TODO_UPDATE_TEXT: null
  });
}).call(this);
