// Generated by LiveScript 1.4.0
/**
 * User: pilagod
 * Date: 7/10/15
 * Time: 12:16 PM
 */
(function(){
  var React, TodoActions, ReactPropTypes, Footer;
  React = require('react');
  TodoActions = require('../actions/TodoActions');
  ReactPropTypes = React.PropTypes;
  Footer = React.createClass({
    propTypes: {
      allTodos: ReactPropTypes.object.isRequired
    },
    render: function(){
      var allTodos, total, completed, i$, len$, todo, itemsLeft, itemsLeftPhrase, clearCompletedButton;
      allTodos = this.props.allTodos;
      total = Object.keys(allTodos).length;
      if (total === 0) {
        return null;
      }
      completed = 0;
      for (i$ = 0, len$ = allTodos.length; i$ < len$; ++i$) {
        todo = allTodos[i$];
        if (todo.complete) {
          completed++;
        }
      }
      itemsLeft = total - completed;
      itemsLeftPhrase = itemsLeft === 1 ? ' item ' : ' items ';
      itemsLeftPhrase += 'left';
      if (completed) {
        clearCompletedButton = (
        <Button
        	id = "clear-completed"
        	onClick = {this._OnClickCompletedClick}>
        	Clear completed ({completed})
        </Button>
        );
      }
      return (
      	<footer id = "footer">
      		<span id = "todo-count">
      			<strong>
      				{itemsLeft}
      			</strong>
      			{itemsLeftPhrase}
      		</span>
      		{clearCompletedButton}
      	</footer>
      );
    },
    _onClearCompletedClick: function(){
      TodoActions.destroyCompleted();
    }
  });
  module.exports = Footer;
}).call(this);
