// Generated by LiveScript 1.4.0
/**
 * User: pilagod
 * Date: 7/10/15
 * Time: 4:23 PM
 */
(function(){
  var React, TodoActions, TodoTextInput, Header;
  React = require('react');
  TodoActions = require('../actions/TodoActions');
  TodoTextInput = require('./TodoTextInput-React');
  Header = React.createClass({
    /**
     *  @return {object}
     */
    render: function(){
      return (
      	<header id="header">
      		<h1>todos</h1>
      		<TodoTextInput
      			id="new-todo"
      			placeholder="What needs to be done?"
      			onSave={this._onSave}
      		/>
      	</header>
      );
    }
    /*
     * @param {string} text
     */,
    _onSave: function(text){
      if (text.trim()) {
        TodoActions.create(text);
      }
    }
  });
  module.exports = Header;
}).call(this);
