// Generated by LiveScript 1.4.0
/**
 * User: pilagod
 * Date: 7/10/15
 * Time: 6:51 PM
 */
(function(){
  var React, TodoActions, TodoItem, ReactPropTypes, MainSection;
  React = require('react');
  TodoActions = require('../actions/TodoActions');
  TodoItem = require('./TodoItem-React');
  ReactPropTypes = React.PropTypes;
  MainSection = React.createClass({
    propTypes: {
      allTodos: ReactPropTypes.object.isRequired,
      areAllComplete: ReactPropTypes.bool.isRequired
    }
    /**
     * @return {object}
     */,
    render: function(){
      var allTodos, todos, i$, ref$, len$, key;
      if (Object.keys(this.props.allTodos).length < 1) {
        return null;
      }
      allTodos = this.props.allTodos;
      todos = [];
      for (i$ = 0, len$ = (ref$ = Object.keys(allTodos)).length; i$ < len$; ++i$) {
        key = ref$[i$];
        todos.push( <TodoItem key={key} todo={allTodos[key]} /> );
      }
      return (
      	<section id="main">
      		<input
      			id="toggle-all"
      			type="checkbox"
      			onChange={this._onToggleCompleteAll}
      			checked={this.props.areAllComplete ? 'checked' : ''}
      		/>
      		<label htmlFor="toggle-all">Mark all as complete</label>
      		<ul id="todo-list">{todos}</ul>
      	</section>
      );
    }
    /**
      * Event handler to mark all TODOs as complete
      */,
    _onToggleCompleteAll: function(){
      TodoActions.toggleCompleteAll();
    }
  });
  module.exports = MainSection;
}).call(this);
