// Generated by LiveScript 1.4.0
/**
 * User: pilagod
 * Date: 7/10/15
 * Time: 4:25 PM
 */
(function(){
  var React, ReactPropTypes, ENTER_KEY_CODE, TodoTextInput;
  React = require('react');
  ReactPropTypes = React.PropTypes;
  ENTER_KEY_CODE = 13;
  TodoTextInput = React.createClass({
    propTypes: {
      className: ReactPropTypes.string,
      id: ReactPropTypes.string,
      placeholder: ReactPropTypes.string,
      onSave: ReactPropTypes.func.isRequired,
      value: ReactPropTypes.string
    },
    getInitialState: function(){
      return {
        value: this.props.value || ''
      };
    }
    /**
      * @return {object}
      */,
    render: function(){
      return (
      	<input
      		className = {this.props.className}
      		id = {this.props.id}
      		placeholder = {this.props.placeholder}
      		onBlur = {this._save}
      		onChange = {this._onChange}
      		onKeyDown = {this._onKeyDown}
      		value = {this.state.value}
      		autoFocus = {true}
      	/>
      );
    }
    /**
      * Invokes the callback passed in as onSave, allowing this component to be
      * used in different ways.
      */,
    _save: function(){
      this.props.onSave(this.state.value);
      this.setState({
        value: ''
      });
    }
    /**
      * @param {object} event
      */,
    _onChange: function(event){
      this.setState({
        value: event.target.value
      });
    }
    /**
      * @param  {object} event
      */,
    _onKeyDown: function(event){
      console.log(event.keyCode);
      if (event.keyCode === ENTER_KEY_CODE) {
        console.log('save');
        this._save();
      }
    }
  });
  module.exports = TodoTextInput;
}).call(this);
