// Generated by LiveScript 1.4.0
/**
 * User: pilagod
 * Date: 7/9/15
 * Time: 11:50 PM
 */
(function(){
  var Dispatcher;
  Dispatcher = require('flux').Dispatcher;
  module.exports = new Dispatcher();
}).call(this);
